---
- name: Setup the workstation with needed packages and tools
  hosts: 127.0.0.1
  connection: local
  vars_files: ./variables.yaml

  pre_tasks:
    - name: Update packages.
      apt:
        update_cache: true
        cache_valid_time: 3600
      changed_when: false
      become: yes

  tasks:

    - name: Execute tasks with escalated priviledges
      block:

        - name: Install needed packages
          apt:
            name: "{{ packages_to_install }}"
            state: present

        - name: Install snap applications
          community.general.snap:
            name: '{{ item }}'
            classic: yes
            state: present
          with_items: "{{ snaps_to_install }}"

        - name: Install Gnome packages
          apt:
            name: "{{ gnome_packages }}"
            state: present
          when: install_gnome == 1
          
      become: yes

    - name: Execute commands without escalated priviledges
      block:

      - name: Install VS Code extensions
        shell: 
          cmd: 'code --install-extension {{ item }}'
        with_items: "{{ vscode_extensions }}"
        when: install_vscode_extensions == 1
        register: code_extensions
        changed_when: "'is already installed.' not in code_extensions.stdout"

      - name: Change desktop background
        shell: 
          cmd: '{{ item }}'
        with_items:
          - gsettings set org.gnome.desktop.background picture-uri ''
          - gsettings set org.gnome.desktop.background primary-color "{{ desktop_color }}"
          - gsettings set org.gnome.desktop.background secondary-color "{{ desktop_color }}"
          - gsettings set org.gnome.desktop.background color-shading-type 'solid'

        when: change_desktop_background == 1
        register: desktop_change
        failed_when: desktop_change.rc == 1
      
      become: no

  post_tasks:

    - name: Clean system packages
      apt:
        autoclean: true
        autoremove: true
      become: yes
